// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWZMPhQDlAroGK2Vq-Gwl_DRN7wydZ0aI',
    appId: '1:974222769885:web:e2159bcdc0a9ce5d06a534',
    messagingSenderId: '974222769885',
    projectId: 'ai-scan-excel',
    authDomain: 'ai-scan-excel.firebaseapp.com',
    storageBucket: 'ai-scan-excel.firebasestorage.app',
    measurementId: 'G-EKTHL3VKT2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXcW-lyQZF2JO3jv2nhR65CE38NkspS4s',
    appId: '1:974222769885:android:5490f6bf35e13cbd06a534',
    messagingSenderId: '974222769885',
    projectId: 'ai-scan-excel',
    storageBucket: 'ai-scan-excel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK5m3FoiD1Zq8lTGdAx8_pDtoToI3UGtw',
    appId: '1:974222769885:ios:22f2ae443ea2b24406a534',
    messagingSenderId: '974222769885',
    projectId: 'ai-scan-excel',
    storageBucket: 'ai-scan-excel.firebasestorage.app',
    iosBundleId: 'com.example.aiScan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK5m3FoiD1Zq8lTGdAx8_pDtoToI3UGtw',
    appId: '1:974222769885:ios:22f2ae443ea2b24406a534',
    messagingSenderId: '974222769885',
    projectId: 'ai-scan-excel',
    storageBucket: 'ai-scan-excel.firebasestorage.app',
    iosBundleId: 'com.example.aiScan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWZMPhQDlAroGK2Vq-Gwl_DRN7wydZ0aI',
    appId: '1:974222769885:web:bf48e287b3fce39406a534',
    messagingSenderId: '974222769885',
    projectId: 'ai-scan-excel',
    authDomain: 'ai-scan-excel.firebaseapp.com',
    storageBucket: 'ai-scan-excel.firebasestorage.app',
    measurementId: 'G-G85H84LE3T',
  );
}
